<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version1_verbe_en extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("INSERT INTO verbe (lang, level, fr, infinitif, form1, form2) VALUES
            ('EN', 2, 'demeurer', 'abide', 'abode', 'abode'),
            ('EN', 2, 's''élever, survenir', 'arise', 'arose', 'arisen'),
            ('EN', 2, '(se) réveiller', 'awake', 'awoke', 'awoken'),
            ('EN', 1, 'être', 'be', 'was', 'been'),
            ('EN', 2, 'supporter', 'bear', 'bore', 'borne'),
            ('EN', 1, 'battre', 'beat', 'beat', 'beaten'),
            ('EN', 1, 'devenir', 'become', 'became', 'become'),
            ('EN', 1, 'commencer', 'begin', 'began', 'begun'),
            ('EN', 2, '(se) courber', 'bend', 'bent', 'bent'),
            ('EN', 1, 'parier', 'bet', 'bet', 'bet'),
            ('EN', 2, 'offrir (un prix)', 'bid', 'bid', 'bid'),
            ('EN', 2, 'lier, relier', 'bind', 'bound', 'bound'),
            ('EN', 2, 'mordre', 'bite', 'bit', 'bitten'),
            ('EN', 2, 'saigner', 'bleed', 'bled', 'bled'),
            ('EN', 1, 'souffler', 'blow', 'blew', 'blown'),
            ('EN', 1, 'casser', 'break', 'broke', 'broken'),
            ('EN', 2, 'élever (du bétail)', 'breed', 'bred', 'bred'),
            ('EN', 1, 'apporter', 'bring', 'brought', 'brought'),
            ('EN', 1, 'construire', 'build', 'built', 'built'),
            ('EN', 1, 'brûler', 'burn', 'burnt', 'burnt'),
            ('EN', 1, 'éclater', 'burst', 'burst', 'burst'),
            ('EN', 1, 'acheter', 'buy', 'bought', 'bought'),
            ('EN', 2, 'jeter, lancer', 'cast', 'cast', 'cast'),
            ('EN', 1, 'attraper', 'catch', 'caught', 'caught'),
            ('EN', 1, 'choisir', 'choose', 'chose', 'chosen'),
            ('EN', 2, 's''accrocher', 'cling', 'clung', 'clung'),
            ('EN', 1, 'venir', 'come', 'came', 'come'),
            ('EN', 1, 'coûter', 'cost', 'cost', 'cost'),
            ('EN', 2, 'ramper', 'creep', 'crept', 'crept'),
            ('EN', 1, 'couper', 'cut', 'cut', 'cut'),
            ('EN', 2, 'distribuer', 'deal', 'dealt', 'dealt'),
            ('EN', 2, 'creuser', 'dig', 'dug', 'dug'),
            ('EN', 1, 'faire', 'do', 'did', 'done'),
            ('EN', 1, 'dessiner', 'draw', 'drew', 'drawn'),
            ('EN', 2, 'rêver', 'dream', 'dreamt', 'dreamt'),
            ('EN', 1, 'boire', 'drink', 'drank', 'drunk'),
            ('EN', 1, 'conduire', 'drive', 'drove', 'driven'),
            ('EN', 2, 'habiter', 'dwell', 'dwelt', 'dwelt'),
            ('EN', 1, 'manger', 'eat', 'ate', 'eaten'),
            ('EN', 1, 'tomber', 'fall', 'fell', 'fallen'),
            ('EN', 1, 'nourrir', 'feed', 'fed', 'fed'),
            ('EN', 1, 'sentir, éprouver', 'feel', 'felt', 'felt'),
            ('EN', 1, 'combattre', 'fight', 'fought', 'fought'),
            ('EN', 1, 'trouver', 'find', 'found', 'found'),
            ('EN', 2, 's''enfuir', 'flee', 'fled', 'fled'),
            ('EN', 2, 'jeter violemment', 'fling', 'flung', 'flung'),
            ('EN', 1, 'voler', 'fly', 'flew', 'flown'),
            ('EN', 1, 'interdire', 'forbid', 'forbade', 'forbidden'),
            ('EN', 1, 'oublier', 'forget', 'forgot', 'forgotten'),
            ('EN', 2, 'pardonner', 'forgive', 'forgave', 'forgiven'),
            ('EN', 2, 'geler', 'freeze', 'froze', 'frozen'),
            ('EN', 1, 'obtenir', 'get', 'got', 'got'),
            ('EN', 1, 'donner', 'give', 'gave', 'given'),
            ('EN', 1, 'aller', 'go', 'went', 'gone'),
            ('EN', 2, 'moudre', 'grind', 'ground', 'ground'),
            ('EN', 1, 'grandir', 'grow', 'grew', 'grown'),
            ('EN', 2, 'pendre, accrocher', 'hang', 'hung', 'hung'),
            ('EN', 1, 'avoir', 'have', 'had', 'had'),
            ('EN', 1, 'entendre', 'hear', 'heard', 'heard'),
            ('EN', 1, '(se) cacher', 'hide', 'hid', 'hidden'),
            ('EN', 1, 'frapper, atteindre', 'hit', 'hit', 'hit'),
            ('EN', 1, 'tenir', 'hold', 'held', 'held'),
            ('EN', 2, 'blesser', 'hurt', 'hurt', 'hurt'),
            ('EN', 1, 'garder', 'keep', 'kept', 'kept'),
            ('EN', 2, 's''agenouiller', 'kneel', 'knelt', 'knelt'),
            ('EN', 1, 'savoir, connaître', 'know', 'knew', 'known'),
            ('EN', 2, 'poser à plat', 'lay', 'laid', 'laid'),
            ('EN', 2, 'mener', 'lead', 'led', 'led'),
            ('EN', 2, 's''appuyer', 'lean', 'leant', 'leant'),
            ('EN', 2, 'sauter', 'leap', 'leapt', 'leapt'),
            ('EN', 2, 'apprendre', 'learn', 'learnt', 'learnt'),
            ('EN', 1, 'laisser, quitter', 'leave', 'left', 'left'),
            ('EN', 2, 'prêter', 'lend', 'lent', 'lent'),
            ('EN', 2, 'permettre, louer', 'let', 'let', 'let'),
            ('EN', 2, 'être étendu', 'lie', 'lay', 'lain'),
            ('EN', 2, 'allumer', 'light', 'lit', 'lit'),
            ('EN', 1, 'perdre', 'lose', 'lost', 'lost'),
            ('EN', 1, 'faire, fabriquer', 'make', 'made', 'made'),
            ('EN', 1, 'signifier', 'mean', 'meant', 'meant'),
            ('EN', 1, '(se) rencontrer', 'meet', 'met', 'met'),
            ('EN', 2, 'tondre', 'mow', 'mowed', 'mown'),
            ('EN', 2, 'surmonter, vaincre', 'overcome', 'overcame', 'overcome'),
            ('EN', 1, 'payer', 'pay', 'paid', 'paid'),
            ('EN', 1, 'mettre', 'put', 'put', 'put'),
            ('EN', 2, 'cesser (de)', 'quit', 'quit', 'quit'),
            ('EN', 1, 'lire', 'read', 'read', 'read'),
            ('EN', 2, 'débarrasser', 'rid', 'rid', 'rid'),
            ('EN', 1, 'chevaucher', 'ride', 'rode', 'ridden'),
            ('EN', 2, 'sonner', 'ring', 'rang', 'rung'),
            ('EN', 2, 's''élever, se lever', 'rise', 'rose', 'risen'),
            ('EN', 1, 'courir', 'run', 'ran', 'run'),
            ('EN', 2, 'scier', 'saw', 'sawed', 'sawn'),
            ('EN', 1, 'dire', 'say', 'said', 'said'),
            ('EN', 1, 'voir', 'see', 'saw', 'seen'),
            ('EN', 2, 'chercher', 'seek', 'sought', 'sought'),
            ('EN', 1, 'vendre', 'sell', 'sold', 'sold'),
            ('EN', 1, 'envoyer', 'send', 'sent', 'sent'),
            ('EN', 2, 'fixer', 'set', 'set', 'set'),
            ('EN', 2, 'coudre', 'sew', 'sewed', 'sewn'),
            ('EN', 1, 'secouer', 'shake', 'shook', 'shaken'),
            ('EN', 2, 'tondre (des moutons)', 'shear', 'sheared', 'shorn'),
            ('EN', 2, 'verser (des larmes)', 'shed', 'shed', 'shed'),
            ('EN', 1, 'briller', 'shine', 'shone', 'shone'),
            ('EN', 2, 'ferrer, chausser', 'shoe', 'shod', 'shod'),
            ('EN', 2, 'tirer', 'shoot', 'shot', 'shot'),
            ('EN', 1, 'montrer', 'show', 'showed', 'shown'),
            ('EN', 2, 'rétrécir', 'shrink', 'shrank', 'shrunk'),
            ('EN', 2, 'fermer', 'shut', 'shut', 'shut'),
            ('EN', 1, 'chanter', 'sing', 'sang', 'sung'),
            ('EN', 2, 'couler', 'sink', 'sank', 'sunk'),
            ('EN', 2, 'être assis', 'sit', 'sat', 'sat'),
            ('EN', 1, 'dormir', 'sleep', 'slept', 'slept'),
            ('EN', 2, 'glisser', 'slide', 'slid', 'slid'),
            ('EN', 2, 'lancer (avec force)', 'sling', 'slung', 'slung'),
            ('EN', 2, 'aller furtivement', 'slink', 'slunk', 'slunk'),
            ('EN', 2, 'fendre, inciser', 'slit', 'slit', 'slit'),
            ('EN', 1, 'sentir (odorat)', 'smell', 'smelt', 'smelt'),
            ('EN', 2, 'semer', 'sow', 'sowed', 'sown'),
            ('EN', 1, 'parler', 'speak', 'spoke', 'spoken'),
            ('EN', 2, 'aller à toute vitesse', 'speed', 'sped', 'sped'),
            ('EN', 2, 'épeler', 'spell', 'spelt', 'spelt'),
            ('EN', 1, 'dépenser', 'spend', 'spent', 'spent'),
            ('EN', 2, 'renverser (un liquide)', 'spill', 'spilt', 'spilt'),
            ('EN', 2, 'cracher', 'spit', 'spat', 'spat'),
            ('EN', 2, 'fendre', 'split', 'split', 'split'),
            ('EN', 2, 'gâcher, gâter', 'spoil', 'spoilt', 'spoilt'),
            ('EN', 2, 'répandre', 'spread', 'spread', 'spread'),
            ('EN', 2, 'jaillir, bondir', 'spring', 'sprang', 'sprung'),
            ('EN', 1, 'être debout', 'stand', 'stood', 'stood'),
            ('EN', 1, 'voler, dérober', 'steal', 'stole', 'stolen'),
            ('EN', 2, 'coller', 'stick', 'stuck', 'stuck'),
            ('EN', 2, 'piquer', 'sting', 'stung', 'stung'),
            ('EN', 2, 'puer', 'stink', 'stank', 'stunk'),
            ('EN', 2, 'marcher à grands pas', 'stride', 'strode', 'stridden'),
            ('EN', 2, 'frapper', 'strike', 'struck', 'struck'),
            ('EN', 2, 'enfiler, tendre (une corde)', 'string', 'strung', 'strung'),
            ('EN', 2, 's''efforcer', 'strive', 'strove', 'striven'),
            ('EN', 2, 'jurer', 'swear', 'swore', 'sworn'),
            ('EN', 2, 'balayer', 'sweep', 'swept', 'swept'),
            ('EN', 2, 'enfler', 'swell', 'swelled', 'swollen'),
            ('EN', 1, 'nager', 'swim', 'swam', 'swum'),
            ('EN', 2, 'se balancer', 'swing', 'swung', 'swung'),
            ('EN', 1, 'prendre', 'take', 'took', 'taken'),
            ('EN', 1, 'enseigner', 'teach', 'taught', 'taught'),
            ('EN', 1, 'déchirer', 'tear', 'tore', 'torn'),
            ('EN', 1, 'dire, raconter', 'tell', 'told', 'told'),
            ('EN', 1, 'penser', 'think', 'thought', 'thought'),
            ('EN', 2, 'jeter', 'throw', 'threw', 'thrown'),
            ('EN', 2, 'enfoncer', 'thrust', 'thrust', 'thrust'),
            ('EN', 2, 'fouler aux pieds', 'tread', 'trod', 'trodden'),
            ('EN', 2, 'subir', 'undergo', 'underwent', 'undergone'),
            ('EN', 1, 'comprendre', 'understand', 'understood', 'understood'),
            ('EN', 2, 'bouleverser', 'upset', 'upset', 'upset'),
            ('EN', 1, '(se) réveiller', 'wake', 'woke', 'woken'),
            ('EN', 1, 'porter (des vêtements)', 'wear', 'wore', 'worn'),
            ('EN', 2, 'tisser', 'weave', 'wove', 'woven'),
            ('EN', 2, 'pleurer', 'weep', 'wept', 'wept'),
            ('EN', 1, 'gagner', 'win', 'won', 'won'),
            ('EN', 2, 'enrouler', 'wind', 'wound', 'wound'),
            ('EN', 2, '(se) retirer', 'withdraw', 'withdrew', 'withdrawn'),
            ('EN', 2, 'tordre', 'wring', 'wrung', 'wrung'),
            ('EN', 1, 'écrire', 'write', 'wrote', 'written')");
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
    }
}
